#############################################################################
# Makefile for building: ExactArithmetic
# Generated by qmake (3.1) (Qt 5.12.3)
# Project:  ../ExactArithmetic/ExactArithmetic.pro
# Template: app
# Command: /media/rob/QtDIsk/Qt/5.12.3/gcc_64/bin/qmake -o Makefile ../ExactArithmetic/ExactArithmetic.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_QML_DEBUG
CFLAGS        = -pipe -g -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -std=gnu++11 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I../ExactArithmetic -I. -I/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/linux-g++
QMAKE         = /media/rob/QtDIsk/Qt/5.12.3/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /media/rob/QtDIsk/Qt/5.12.3/gcc_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /media/rob/QtDIsk/Qt/5.12.3/gcc_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = ExactArithmetic1.0.0
DISTDIR = /home/rob/build-ExactArithmetic-Desktop_Qt_5_12_3_GCC_64bit-Debug/.tmp/ExactArithmetic1.0.0
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS) -lboost_unit_test_framework   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ../ExactArithmetic/boosttests.cpp \
		../ExactArithmetic/gcd.cpp \
		../ExactArithmetic/integer.cpp \
		../ExactArithmetic/main.cpp \
		../ExactArithmetic/rational.cpp 
OBJECTS       = boosttests.o \
		gcd.o \
		integer.o \
		main.o \
		rational.o
DIST          = /media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/features/spec_pre.prf \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/common/unix.conf \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/common/linux.conf \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/common/sanitize.conf \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/common/gcc-base.conf \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/common/g++-base.conf \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/common/g++-unix.conf \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/qconfig.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_repparser.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/features/qt_functions.prf \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/features/qt_config.prf \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/linux-g++/qmake.conf \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/features/spec_post.prf \
		../ExactArithmetic/.qmake.stash \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/features/exclusive_builds.prf \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/features/toolchain.prf \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/features/default_pre.prf \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/features/resolve_config.prf \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/features/default_post.prf \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/features/qml_debug.prf \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/features/warn_on.prf \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/features/qmake_use.prf \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/features/file_copies.prf \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/features/testcase_targets.prf \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/features/exceptions.prf \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/features/yacc.prf \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/features/lex.prf \
		../ExactArithmetic/ExactArithmetic.pro dividebyzeroerror.h \
		gcd.h \
		integer.h \
		rational.h ../ExactArithmetic/boosttests.cpp \
		../ExactArithmetic/gcd.cpp \
		../ExactArithmetic/integer.cpp \
		../ExactArithmetic/main.cpp \
		../ExactArithmetic/rational.cpp
QMAKE_TARGET  = ExactArithmetic
DESTDIR       = 
TARGET        = ExactArithmetic


first: all
####### Build rules

ExactArithmetic:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ../ExactArithmetic/ExactArithmetic.pro /media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/linux-g++/qmake.conf /media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/features/spec_pre.prf \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/common/unix.conf \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/common/linux.conf \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/common/sanitize.conf \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/common/gcc-base.conf \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/common/g++-base.conf \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/common/g++-unix.conf \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/qconfig.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_repparser.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/features/qt_functions.prf \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/features/qt_config.prf \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/linux-g++/qmake.conf \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/features/exclusive_builds.prf \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/features/toolchain.prf \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/features/default_pre.prf \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/features/resolve_config.prf \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/features/default_post.prf \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/features/qml_debug.prf \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/features/warn_on.prf \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/features/qmake_use.prf \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/features/file_copies.prf \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/features/testcase_targets.prf \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/features/exceptions.prf \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/features/yacc.prf \
		/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/features/lex.prf \
		../ExactArithmetic/ExactArithmetic.pro
	$(QMAKE) -o Makefile ../ExactArithmetic/ExactArithmetic.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/features/spec_pre.prf:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/common/unix.conf:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/common/linux.conf:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/common/sanitize.conf:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/common/gcc-base.conf:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/common/gcc-base-unix.conf:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/common/g++-base.conf:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/common/g++-unix.conf:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/qconfig.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3danimation.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dextras.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_charts.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_charts_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_core.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_designer.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_gamepad.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_gui.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_help.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_location.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_network.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_networkauth.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_purchasing.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qml.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quick.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_repparser.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_script.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_scxml.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_sql.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_svg.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webview.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_xml.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/features/qt_functions.prf:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/features/qt_config.prf:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/linux-g++/qmake.conf:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/features/spec_post.prf:
.qmake.stash:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/features/exclusive_builds.prf:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/features/toolchain.prf:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/features/default_pre.prf:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/features/resolve_config.prf:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/features/default_post.prf:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/features/qml_debug.prf:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/features/warn_on.prf:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/features/qmake_use.prf:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/features/file_copies.prf:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/features/testcase_targets.prf:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/features/exceptions.prf:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/features/yacc.prf:
/media/rob/QtDIsk/Qt/5.12.3/gcc_64/mkspecs/features/lex.prf:
../ExactArithmetic/ExactArithmetic.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile ../ExactArithmetic/ExactArithmetic.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile ExactArithmetic

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

check: first

benchmark: first

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

boosttests.o: ../ExactArithmetic/boosttests.cpp ../ExactArithmetic/integer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o boosttests.o ../ExactArithmetic/boosttests.cpp

gcd.o: ../ExactArithmetic/gcd.cpp ../ExactArithmetic/gcd.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gcd.o ../ExactArithmetic/gcd.cpp

integer.o: ../ExactArithmetic/integer.cpp ../ExactArithmetic/integer.h \
		../ExactArithmetic/dividebyzeroerror.h \
		../ExactArithmetic/gcd.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o integer.o ../ExactArithmetic/integer.cpp

main.o: ../ExactArithmetic/main.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o ../ExactArithmetic/main.cpp

rational.o: ../ExactArithmetic/rational.cpp ../ExactArithmetic/rational.h \
		../ExactArithmetic/dividebyzeroerror.h \
		../ExactArithmetic/gcd.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rational.o ../ExactArithmetic/rational.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

